CREATE DATABASE simoldes;

create table simoldes.funcionarios (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    CARGO VARCHAR(80) NOT NULL,
    MATRICULA VARCHAR(20) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    PALAVRA VARCHAR(50) NOT NULL
);

create table simoldes.plano_vale (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    VALE_TRANSPORTE VARCHAR(1),
    PLANO_ODONTOLOGICO VARCHAR(1),
    PLANO_SAUDE VARCHAR(1),
    COMENTARIO VARCHAR(100),
    DATA_INSERC DATETIME DEFAULT NOW(),
    VALIDADO VARCHAR(1) DEFAULT 'N'
);